# Site settings
title: Patrick Tulskie
email: patricktulskie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Patrick Tulskie dot com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://patricktulskie.com" # the base hostname & protocol for your site
twitter_username: patricktulskie
github_username:  patricktulskie
permalink: posts/:year/:month/:title/
logo:
  url: "img/sunglasses.jpg"

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
