version: '3'

services:
  jekyll:
    build: .
    image: "patricktulskie/jekyll"
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
